### PR TITLE
fix .d.ts: declare global is very important

### PR DESCRIPTION
**Pull request by xialvjun**
https://github.com/Microsoft/TypeScript/issues/22321#issuecomment-392736683

https://github.com/Microsoft/TypeScript/issues/24452

like https://github.com/thysultan/stylis.js

### CODE REVIEW

**Comment by xialvjun** [comment]
no, things are wrong...

**error**
```ts
export = EventEmitter;
declare global {
  export const EventEmitter: EventEmitter
}

import * as EventEmitter from '@nodeart/event_emitter';
```
> has nothing to do with `declare global`;

**error**
```ts
declare const event_emitter: EventEmitter
export = event_emitter;

import * as EventEmitter from '@nodeart/event_emitter'; // OK
// error: Type 'EventEmitter' is not a constructor function type.
class A extends EventEmitter {}
```

**error**
```ts
export default EventEmitter;

import EventEmitter from '@nodeart/event_emitter'; // OK
class A extends EventEmitter {} // OK

// but the generated js is wrong unless tsconfig.compilerOption.esModuleInterop=true... dependency should not affect project's tsconfig too much
```

```ts
export = EventEmitter;

import EventEmitter = require('@nodeart/event_emitter'); // OK
class A extends EventEmitter {} // OK

// it did ok, but it require the project's tsconfig.compilerOption.module='commonjs'
```

I don't know if there is a solution or just a typescript bug.

**Comment by xialvjun** [comment]
well, learn from https://github.com/thysultan/stylis.js, we can

```ts
interface EventEmitter {
  new(): EventEmitter
  readonly _events: Map<string, {fn: Function, times?: number, count?: number}>
  once(eventName: string, ...fns: Function[]): this
  times(eventName: string, times?: number, ...fns: Function[]): this
  on(eventName: string, ...fns: Function[]): this
  emit(eventName: string, ctx?: any, ...args: any[]): this
  off(eventName: string, ...fns: Function[]): this
  offAll(): this

  // don't know how to show these two methods are static
  inherit(successor: any): any
  extend(successor: any): any
}
declare const event_emitter: EventEmitter;
export = event_emitter;

import * as EventEmitter from '@nodeart/event_emitter'; // OK
class A extends EventEmitter {} // OK
```

**Comment by IvanProdaiko94** [comment]
thanks a lot for contribution @xialvjun, but I think that the best solution we could come up with is to substitute current d.ts file with this content:
```typescript
export declare class EventEmitter {
  readonly _events: Map<string, {fn: Function, times?: number, count?: number}>
  once(eventName: string, ...fns: Function[]): this
  times(eventName: string, times?: number, ...fns: Function[]): this
  on(eventName: string, ...fns: Function[]): this
  emit(eventName: string, ctx?: any = null, ...args: any[]): this
  off(eventName: string, ...fns: Function[]): this
  offAll(): this
  static inherit(successor: any): any
  static extend(successor: any): any
}
```
Basically add `export` statement. 
Than usage will be as fallows:
```typescript
import { EventEmitter } from "@nodeart/event_emitter";

class X extends EventEmitter {

}
```

**Comment by IvanProdaiko94** [comment]
@xialvjun if you are ok with it, I would rather close PR or change it to content mentioned above

**Comment by xialvjun** [comment]
Then, you need to change the js file. That maybe a break change. Or you can `EventEmitter.EventEmitter=EventEmitter` to make it compatible with old code.

**Comment by IvanProdaiko94** [comment]
No, I don't need to change js file. Why should I?

**Comment by xialvjun** [comment]
If you not change js file. then `import { EventEmitter } from "@nodeart/event_emitter";` will get `EventEmitter === undefined`

**Comment by IvanProdaiko94** [comment]
Oh, now I see.

**Comment by IvanProdaiko94** [comment]
@xialvjun could you please share your

**Comment by xialvjun** [comment]
？？？？？ don't merge。。。。   this is just a discussion. 
if you prefer
```ts
import { EventEmitter } from "@nodeart/event_emitter";

class X extends EventEmitter {

}
```

then you should change js file to
```js
EventEmitter.EventEmitter = EventEmitter;
module.exports = EventEmitter;
```

and .d.ts
```ts
export declare class EventEmitter {
  xxxxxx
}
```

**Comment by IvanProdaiko94** [comment]
@xialvjun so did I)

**Comment by xialvjun** [comment]
nice...👍👍👍👍👍👍👍

**Pull request merged**
